version: "3"
services:
  vehicle-db:
    image: "postgres"
    container_name: "db-vehicle"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vehicle-db
    ports:
      - "5432:5432"
  rent-management-db:
    image: "postgres"
    container_name: "db-rent-management"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rent-db
    ports:
      - "5433:5432"

  users-system-db:
    image: "postgres"
    container_name: "db-users"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users-db
    ports:
      - "5434:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  users-service:
    build: ./users-service
    container_name: users-service_container
    depends_on:
      - kafka
      - zookeeper
      - users-system-db

  rent-management:
    build: ./rent-management
    container_name: rent-management_container
    depends_on:
      - kafka
      - zookeeper
      - rent-management-db

  vehicle-list:
    build: ./vehicle-list
    container_name: vehicle-list_container
    depends_on:
      - kafka
      - zookeeper
      - vehicle-db


